### ISSUE TITLE
Naming for core tokens

### ISSUE THREAD

**Issue by lukasoppermann** [telekom/design-tokens#12]
How can we name core tokens so that they are easy to understand and still be changeable.

### Issue to solve:
Currently some tokens are named in a way that they are tightly coupled to their value, e.g. `spacing-2 = 2px`

We need to change this to allow us and other users to change the core tokens, e.g. to allow theming, without having to recode all components.

### Namings
- [x]  **radius**: sm, md, lg, circle, pill see #21 
- [x]  **elevation**: level #25 
- [x]  **lineWeight**: tshirt
- [x]  **motion**: scale is mostly fine
- [x]  **opacity**: low/high scale #22
- [x]  **spacing**: 4 groups from small to extra-large with 3 items each #23
- [x]  **Typography** #26 
    - [x]  **lineSpacing**: tshirt
    - [x]  **fontSize**: grouped small to large
    - [x]  **letterspacing**: not needed for now -> only one, default
    - [x]  **fontWeight** (default font weight names)
    - [x]  **Families**: sans, mono, (serif, display, variable)
- [x]  **zIndex**: levels #24
